#ifndef OTA_CONFIG_H
#define OTA_CONFIG_H

#include <stdint.h>

#if !defined(__STDC_VERSION__) || (__STDC_VERSION__ < 201112L)
#error "OTA firmware requires a C11 compiler"
#endif

#define OTA_KIBIBYTE UINT32_C(1024)

#define OTA_FLASH_START UINT32_C(0x00000000)
#define OTA_FLASH_SIZE (UINT32_C(256) * OTA_KIBIBYTE)
#define OTA_FLASH_END (OTA_FLASH_START + OTA_FLASH_SIZE)
#define OTA_FLASH_PAGE_SIZE OTA_KIBIBYTE

#define OTA_BOOTLOADER_START OTA_FLASH_START
#define OTA_BOOTLOADER_SIZE (UINT32_C(32) * OTA_KIBIBYTE)

#define OTA_SLOT_A_START (OTA_BOOTLOADER_START + OTA_BOOTLOADER_SIZE)
#define OTA_SLOT_SIZE (UINT32_C(111) * OTA_KIBIBYTE)
#define OTA_SLOT_COUNT UINT32_C(2)
#define OTA_SLOT_B_START (OTA_SLOT_A_START + OTA_SLOT_SIZE)
#define OTA_SLOT_HEADER_SIZE OTA_FLASH_PAGE_SIZE
#define OTA_SLOT_A_PAYLOAD_START (OTA_SLOT_A_START + OTA_SLOT_HEADER_SIZE)
#define OTA_SLOT_B_PAYLOAD_START (OTA_SLOT_B_START + OTA_SLOT_HEADER_SIZE)
#define OTA_SLOT_PAYLOAD_SIZE (OTA_SLOT_SIZE - OTA_SLOT_HEADER_SIZE)

#define OTA_METADATA_COPY0_START (OTA_SLOT_B_START + OTA_SLOT_SIZE)
#define OTA_METADATA_COPY1_START (OTA_METADATA_COPY0_START + OTA_FLASH_PAGE_SIZE)
#define OTA_METADATA_COPY_SIZE OTA_FLASH_PAGE_SIZE
#define OTA_METADATA_COPY_COUNT UINT32_C(2)

#define OTA_SRAM_START UINT32_C(0x20000000)
#define OTA_SRAM_SIZE (UINT32_C(32) * OTA_KIBIBYTE)
#define OTA_SRAM_END (OTA_SRAM_START + OTA_SRAM_SIZE)

#define OTA_DEBUG_UART_INSTANCE UINT8_C(0)
#define OTA_OTA_UART_INSTANCE UINT8_C(1)
#define OTA_GPIO_PORT_B_INDEX UINT8_C(1)
#define OTA_OTA_UART_RX_GPIO_PORT_INDEX OTA_GPIO_PORT_B_INDEX
#define OTA_OTA_UART_RX_GPIO_PIN_INDEX UINT8_C(0)
#define OTA_OTA_UART_TX_GPIO_PORT_INDEX OTA_GPIO_PORT_B_INDEX
#define OTA_OTA_UART_TX_GPIO_PIN_INDEX UINT8_C(1)

#define OTA_UART1_BAUD_RATE UINT32_C(115200)
#define OTA_UART1_DATA_BITS UINT8_C(8)
#define OTA_UART1_STOP_BITS UINT8_C(1)
#define OTA_UART1_PARITY_NONE UINT8_C(0)

#define OTA_PROTOCOL_SOF0 UINT8_C(0x55)
#define OTA_PROTOCOL_SOF1 UINT8_C(0xAA)
#define OTA_PROTOCOL_SOF_SIZE UINT8_C(2)
#define OTA_PROTOCOL_VERSION UINT8_C(1)
#define OTA_PROTOCOL_FIXED_HEADER_SIZE UINT8_C(6)
#define OTA_PROTOCOL_MAX_PAYLOAD_SIZE UINT16_C(256)
#define OTA_PROTOCOL_CRC_SIZE UINT8_C(4)

#define OTA_CRC32_INITIAL_VALUE UINT32_C(0xffffffff)
#define OTA_CRC32_FINAL_XOR UINT32_C(0xffffffff)
#define OTA_CRC32_REFLECTED_POLYNOMIAL UINT32_C(0xEDB88320)

#define OTA_PACKET_TIMEOUT_MS UINT32_C(1000)
#define OTA_RESPONSE_TIMEOUT_MS UINT32_C(1000)
#define OTA_MAX_RETRIES UINT32_C(3)
#define OTA_PENDING_BOOT_MAX_ATTEMPTS UINT32_C(3)

#endif
